# gevent monkey-patch MUST be the very first thing — before any other import.
# This replaces stdlib threading, socket, ssl, and time with gevent-aware
# equivalents, making all I/O (Redis, Kafka, Postgres, HTTP) non-blocking.
# Nothing in qf-framework uses threads that cannot be patched.
import gevent.monkey
gevent.monkey.patch_all()

"""
Application entry point.

Starts the Kafka ETL consumer (background thread) and the Flask HTTP API
(main thread) in a single process.

Environment quick-start
-----------------------
    # 1. Start infrastructure
    docker compose up -d

    # 2. Run with defaults (no tracing)
    python main.py

    # 3. Run with Jaeger tracing
    ENABLE_TRACING=true OTLP_ENDPOINT=http://localhost:4317 python main.py

    # 4. Verify
    curl http://localhost:5000/health
"""

import os
import sys
from pathlib import Path

# ---------------------------------------------------------------------------
# Path setup — makes src/ and the framework src/ importable.
# In a packaged project these would be installed; this shim keeps the
# template self-contained without requiring pip install -e.
# ---------------------------------------------------------------------------
BASE_DIR = Path(__file__).resolve().parent
sys.path.insert(0, str(BASE_DIR / "src"))           # config, workers, service, instances
sys.path.insert(0, str(BASE_DIR.parent / "src"))    # framework/

from src.config import Config
from framework.app import FrameworkApp, FrameworkSettings
from framework.commons.logger import logger


def main() -> None:
    logger.info(
        f"[{Config.APP_NAME}] starting — "
        f"tracing={'on' if Config.ENABLE_TRACING else 'off'} "
        f"kafka={Config.KAFKA_BOOTSTRAP_SERVERS} "
        f"port={Config.API_PORT}"
    )

    settings = FrameworkSettings(
        enable_etl=True,
        enable_api=True,
        enable_dynamic_endpoints=True,

        # HTTP API
        api_host="0.0.0.0",
        api_port=Config.API_PORT,
        api_version="1.0",
        api_title=f"{Config.APP_NAME} API",
        api_description="Generated by qf-template",
        endpoint_json_path="maps/endpoint.json",

        # Kafka ETL
        worker_modules=["workers.workers"],
        kafka_bootstrap_servers=Config.KAFKA_BOOTSTRAP_SERVERS,
        consumer_name=Config.WORKER_NAME,

        # Tracing
        enable_tracing=Config.ENABLE_TRACING,
        otlp_endpoint=Config.OTLP_ENDPOINT,
        service_name=Config.APP_NAME,
    )

    fw = FrameworkApp(settings, app_root=BASE_DIR)
    handles = fw.run()

    if handles.app:
        logger.info(f"[{Config.APP_NAME}] HTTP API on 0.0.0.0:{Config.API_PORT}")
        handles.app.run(host="0.0.0.0", port=Config.API_PORT, debug=False)


if __name__ == "__main__":
    main()
